---
# tasks file for webserver

- name: Ensure httpd is installed and running 
  package:
    name: httpd
    state: present

- name: Deploy index.html template 
  template:
    src: index.html.j2 
    dest: /var/www/html/index.html 
